### ISSUE TITLE
Project spec as YAML/JSON

### ISSUE THREAD

**Issue by HamishBuckmaster** [railwayapp/cli#263]
## Purpose 

I'd like to confirm / create services from a json something along the lines of

```json
{
  "environments": [
    {
      "name": "production",
      "plugins": [
        {
          "type": "postgres"
        },
        {
          "type": "redis"
        }
      ]
    }
  ]
}

```

**Comment by espensgr** [comment]
I was thinking the same thing!
But take a look at [Digital Ocean app spec](https://docs.digitalocean.com/products/app-platform/reference/app-spec/) as it is about the same type of setup.
And in DO you can copy or download the file/spec to use it.
Maybe change the title of this issue to "Project spec as YAML/JSON"?

**Comment by HamishBuckmaster** [comment]
> I was thinking the same thing! But take a look at [Digital Ocean app spec](https://docs.digitalocean.com/products/app-platform/reference/app-spec/) as it is about the same type of setup. And in DO you can copy or download the file/spec to use it, super easy to spin up an existing stack to a new project. Maybe change the title of this issue to "Project spec as YAML/JSON"?
> 
> This would also open up the platform for a range of uses and short comings that the templates dont address today.

That's a great idea, updated the title!

Yeah something similar to the digital ocean spec would be great

**Comment by JakeCooper** [comment]
> This would also open up the platform for a range of uses and short comings that the templates dont address today.

Can you list these shortcomings?

**Comment by espensgr** [comment]
Sure can.

The template system today is only made for sharing a stack with other people, that also means that they have to clone the repos on init to use it, not just use it as is. It also only deals with the init of a project, no update/deleting/adding items in the stack.
I think the template is good for it's specific use case, but it is too narrow to do more with the platform.

With a project spec you can have the template on top of that, using the spec as a staring point and then change varies settings/items in one move. As of now you cant copy an existing stack, i have to make the same stack manually every time.

Let's say i have made a product i'm selling and i have 4 items in the stack of that product: web, cli, db and cache. I cant make this with the template as it clones the repo and i cant change it over time. And since there is no api at this time i cant really change the stack later down the line, i have to do it via the control panel.

A project spec solves a lot of things and makes the use cases for the platform larger in my opinion, maybe things i cant even see at this point.
It is a good reason that Digital Ocean implemented this on the app platform, usability and complexity in on go. You can go as narrow or wide as you like with it.

**Comment by coffee-cup** [comment]
This is indeed something we are looking at adding to Railway. But it spans much more than just the CLI. I'm going to close this issue here and recommend that you follow along with the feature request on Canny for updates

https://railway.canny.io/feature-requests/p/infrastructure-as-code
