### ISSUE TITLE
HTTP status client error (413 Payload Too Large) for url

### ISSUE THREAD

**Issue by cyriaque-ovaga** [railwayapp/cli#401]
Hello I use Gitlab to make my CI/CD. I have a code that weighs 270MB. But when I run I get the message:
$railway up --service=$RAILWAY_SERVICE_NAME -d
Indexing...
Download...
Error: HTTP Status Client Error (413 Payload Too Large) for URL (https://backboard.railway.app/project/baexxxxx/environment/xxxxx/up?serviceId=xxxxx)

Help me

**Comment by sandervspl** [comment]
I'm also getting this error running `railway up` from my terminal.

**Comment by jensdanb** [comment]
> I'm also getting this error running `railway up` from my terminal. With node_modules included, my code is around 240MB.

Same here. I did some testing now with my Python webapp: 
With just a simple main.py file and a new venv file in directory, it is ~4KiB and deployment works. 

When I copy requirements.txt from my app (developed in another repo) into the railway repo and install them (pip install -r requirements.txt), the repo grows as expected to ~250MiB. If I then execute 'railway up', I get error code 413. 

I'm on the starter plan, since I'm new to railway, it says I currently have up to 512 MB container memory, so it should be enough? My project doesn't include any large datasets or heavy computations, so I had expected it to be deployable with the starter plan. I can see myself using a bigger plan, but I want to see if it at all works first.

**Comment by sandervspl** [comment]
@jensdanb I resolved my issue and for me it was the .git folder. The CLI does not ignore it my default. I needed to add it to my `.gitignore` and then it worked. See #404

**Comment by jensdanb** [comment]
@sandervspl thanks! I didn't see your comment before and went to Linode, but UX here on Railways was quite a bit nicer, so might come back.
